In [1]:
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier

# Load NCVS data into a pandas dataframe
df = pd.read_table('38090-0005-Data.tsv')



In [2]:
for index, row in df.iterrows():
    #Assault
    if (row["V4529"] == 11 or row["V4529"] == 12 or row["V4529"] == 13 or row["V4529"] == 14 or row["V4529"] == 17 or row["V4529"] == 20):
        df.at[index,"V4529"] = 3


In [3]:

print(df["V4529"].value_counts())

56    1524
3     1358
57    1244
55     991
58     635
32     542
54     422
59     352
31     247
40     213
33     180
41      63
7       48
1       44
10      34
15      23
5       23
23      22
6       21
2       18
9       10
18       9
19       6
8        6
4        2
16       2
22       2
21       2
Name: V4529, dtype: int64


In [4]:
df_assault = df.loc[df["V4529"] == 3]
df_assault
    

V2001   YEARQ                       IDHH                        IDPER  \
7         2  2020.1  1602073992355333564544321  160207399235533356454432101   
8         2  2020.1  1602073992355333564544321  160207399235533356454432101   
9         2  2020.1  1602073992355333564544321  160207399235533356454432101   
10        2  2020.1  1602073992355333564544321  160207399235533356454432101   
13        2  2020.1  1602091992688989565949137  160209199268898956594913701   
...     ...     ...                        ...                          ...   
8036      2  2020.4  1998941684460892565945147  199894168446089256594514703   
8037      2  2020.4  1998941684460892565945147  199894168446089256594514703   
8038      2  2020.4  1998941684460892565945147  199894168446089256594514703   
8039      2  2020.4  1998944199680097565959147  199894419968009756595914702   
8040      2  2020.4  1998944199680097565959147  199894419968009756595914702   

      V2002  V2003  V2004                 V2005  V2006  V2008  ...  \
7         8    201     16  02073992355333564544      3     21  ...   
8         8    201     16  02073992355333564544      3     21  ...   
9         8    201     16  02073992355333564544      3     21  ...   
10        8    201     16  02073992355333564544      3     21  ...   
13        8    201     16  02091992688989565949      1     37  ...   
...     ...    ...    ...                   ...    ...    ...  ...   
8036      3    204     19  98941684460892565945      1     47  ...   
8037      3    204     19  98941684460892565945      1     47  ...   
8038      3    204     19  98941684460892565945      1     47  ...   
8039      2    204     19  98944199680097565959      1     47  ...   
8040      2    204     19  98944199680097565959      1     47  ...   

      VICREPWGT151  VICREPWGT152  VICREPWGT153  VICREPWGT154  VICREPWGT155  \
7        401.61681    2528.89547    2434.93769    1419.86393    1523.06432   
8        401.61681    2528.89547    2434.93769    1419.86393    1523.06432   
9        401.61681    2528.89547    2434.93769    1419.86393    1523.06432   
10       401.61681    2528.89547    2434.93769    1419.86393    1523.06432   
13       501.42554    3257.86903     452.83591    1743.29210     579.87993   
...            ...           ...           ...           ...           ...   
8036    8156.47940    1762.91979    1862.31765    2022.56997    1603.27339   
8037    8156.47940    1762.91979    1862.31765    2022.56997    1603.27339   
8038    8156.47940    1762.91979    1862.31765    2022.56997    1603.27339   
8039    1477.63461    1558.81562    1693.76975    1652.97013     547.66168   
8040    1477.63461    1558.81562    1693.76975    1652.97013     547.66168   

      VICREPWGT156  VICREPWGT157  VICREPWGT158  VICREPWGT159  VICREPWGT160  
7        460.96821    1548.28375    1510.67039    1437.07934    1365.19375  
8        460.96821    1548.28375    1510.67039    1437.07934    1365.19375  
9        460.96821    1548.28375    1510.67039    1437.07934    1365.19375  
10       460.96821    1548.28375    1510.67039    1437.07934    1365.19375  
13       432.09296    1585.19116    1971.74981    1911.35400    1546.80260  
...            ...           ...           ...           ...           ...  
8036    6232.84066    1391.36558    6663.19618    1882.87691    8713.14869  
8037    6232.84066    1391.36558    6663.19618    1882.87691    8713.14869  
8038    6232.84066    1391.36558    6663.19618    1882.87691    8713.14869  
8039     465.86033    1533.80035    2873.30205    1494.86541    2309.67967  
8040     465.86033    1533.80035    2873.30205    1494.86541    2309.67967  

[1358 rows x 1496 columns]

In [5]:
#how mant times
print(df_assault["V4017"].value_counts())

1    1298
2      52
8       8
Name: V4017, dtype: int64


In [6]:
#HOW MANY IN THE LAST 6 MONTHS
print(df_assault["V4016"].value_counts())

1      1028
2       135
3        66
4        35
5        34
10       14
997       8
6         8
12        7
30        6
7         5
20        4
8         2
15        1
26        1
11        1
24        1
25        1
17        1
Name: V4016, dtype: int64


In [7]:
#HATE CRIME
print(df_assault["V4526AA"].value_counts())

2    1225
1     115
3      11
8       7
Name: V4526AA, dtype: int64


In [8]:
#location urbanicity
#one-hot
df_assault["V2143"].value_counts()


2    931
3    246
1    181
Name: V2143, dtype: int64

In [9]:
#race of house hold head
#everything is 99 not helpful
df_assault["V2031"].value_counts()

99    1358
Name: V2031, dtype: int64

In [10]:
#we are confused if its helpful
df_assault["V2032"].value_counts()

11    1069
2      289
Name: V2032, dtype: int64

In [11]:
#no of hh members 12+
#one-hot
df_assault["V2071"].value_counts()

2    499
1    414
3    254
4    130
5     38
6     16
7      6
8      1
Name: V2071, dtype: int64

In [12]:
#individual emeployment info
#binary

df_assault["V3071"].value_counts()

1    856
2    444
9     54
8      4
Name: V3071, dtype: int64

In [13]:
#location of the incident
#one-hot
df_assault["V4022"].value_counts()

3    956
4    374
2     13
1      8
8      4
5      3
Name: V4022, dtype: int64

In [14]:
#if the offender had a right to be there
#add but has lots of 9
df_assault["V4025"].value_counts()

9    1113
1     182
2      63
Name: V4025, dtype: int64

In [15]:
#evidence of forced entry
#doesnt apply well to assault cases
df_assault["V4029"].value_counts()

9    1346
1      11
8       1
Name: V4029, dtype: int64

In [16]:
#received medical care
#next iteration, probably should not use it. 
df_assault["V4127"].value_counts()

9    1105
2     147
1     106
Name: V4127, dtype: int64

In [17]:
#anyone other than the respondent present
df_assault["V4184"].value_counts()

1    773
2    465
8    104
3     16
Name: V4184, dtype: int64

In [18]:
#one or more offender
#next iteration
df_assault["V4234"].value_counts()

1    1168
2     132
8      40
3      18
Name: V4234, dtype: int64

In [19]:
#value of property taken
#next iteration --doesnt help
df_assault["V4364"].value_counts()

99999    1358
Name: V4364, dtype: int64

In [20]:
#incident occur at work
#next iteration-not useful
df_assault["V4484"].value_counts()

9    1023
1     313
2      15
8       5
3       1
4       1
Name: V4484, dtype: int64

In [21]:
#same thing happen each time
#next iteration - not useful
df_assault["V4524"].value_counts()

9    1303
1      42
8       9
2       4
Name: V4524, dtype: int64

In [22]:
#is trouble still going on
#next iteration--not useful
df_assault["V4525"].value_counts()

9    1303
1      28
2      18
8       9
Name: V4525, dtype: int64

In [68]:
#Relationship to offender
#df_assault["V4523"].value_counts()
df["V4522F"].value_counts()

9    7958
0      63
8      20
1       2
Name: V4522F, dtype: int64

In [23]:
inputs = df_assault[["V4017","V4016","V4526AA","V2143","V2032","V2071","V3071","V4022","V4025","V4184","V4234"]]
target = df_assault[['V4399']]
df_assault["V4399"].value_counts()

2    724
1    604
3     26
8      4
Name: V4399, dtype: int64

In [24]:
604/(604+724)


0.45481927710843373

In [25]:
724/(604+724)

0.5451807228915663

In [26]:
#normalizing data
scaler = preprocessing.StandardScaler().fit(inputs)
scaled_inputs = scaler.transform(inputs)
scaled_inputs 

array([[-0.1404508 , -0.03568331, -1.81568887, ..., -2.21346548,
         0.05368263, -0.27074513],
       [-0.1404508 , -0.03568331, -1.81568887, ..., -2.21346548,
         0.05368263, -0.27074513],
       [-0.1404508 , -0.03568331, -1.81568887, ..., -2.21346548,
         0.05368263, -0.27074513],
       ...,
       [-0.1404508 , -0.06192644,  0.08686166, ...,  0.46826631,
        -0.49444527, -0.27074513],
       [-0.1404508 , -0.08816958,  0.08686166, ..., -1.87824901,
        -0.49444527, -0.27074513],
       [-0.1404508 , -0.08816958,  0.08686166, ...,  0.46826631,
        -0.49444527, -0.27074513]])

In [27]:
#splitting data to train and test splits
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, target, test_size=0.2, random_state=42)
X_train
print(y_train)

      V4399
5027      1
7647      1
2126      2
4120      1
308       1
...     ...
6504      2
6693      2
7685      1
4995      1
6686      1

[1086 rows x 1 columns]


In [28]:
#training a logistic regression model
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)
clf.score(X_train,y_train)

/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5939226519337016

In [29]:
#Random Forest
rmf = RandomForestClassifier(n_estimators=200,max_depth=5, random_state=0,criterion="entropy")
rmf.fit(X_train, y_train)
rmf.score(X_test,y_test)

/tmp/ipykernel_2077151/1354861141.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rmf.fit(X_train, y_train)


0.6102941176470589

In [30]:
y_pred = rmf.predict(X_test)

# Evaluate performance
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.61      0.57      0.59       128
           2       0.61      0.67      0.64       139
           3       0.00      0.00      0.00         5

    accuracy                           0.61       272
   macro avg       0.41      0.41      0.41       272
weighted avg       0.60      0.61      0.60       272

[[73 55  0]
 [46 93  0]
 [ 1  4  0]]


/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division`

In [31]:
# Define hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 200,300],
    'max_depth': [2,5, 10, None]
}

# Search over hyperparameter grid
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(rmf, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Print best hyperparameters
print(grid_search.best_params_)

/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/s

{'max_depth': 5, 'n_estimators': 200}


In [32]:
rmf.score(X_test,y_test)

0.6102941176470589

In [33]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train)

neigh.score(X_test,y_test)

/opt/pub/eb/apps/all/DavidsonJupyter/2021-common-GCCcore-10.2.0/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


0.5257352941176471

In [80]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Load and preprocess NCVS data
data = df_assault
# ... data cleaning and feature selection ...

# Split data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(scaled_inputs, target, test_size=0.2)

# Convert data and labels to PyTorch tensors
train_data_tensor = torch.tensor(train_data.astype(np.float32))
train_labels_tensor = torch.tensor(train_labels.values.astype(np.float32))
test_data_tensor = torch.tensor(test_data.astype(np.float32))
test_labels_tensor = torch.tensor(test_labels.values.astype(np.float32))

# Define neural network model
class MyModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyModel, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
        self.activation = nn.ReLU()
        
    def forward(self, x):
        x = self.layer1(x)
        x = self.activation(x)
        x = self.layer2(x)
        return x

# Set up model, loss function, and optimizer
model = MyModel(train_data.shape[1], 64, 1)
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train model on training data
for epoch in range(50):
    optimizer.zero_grad()
    output = model(train_data_tensor)
    loss = criterion(output, train_labels_tensor.view(-1, 1))
    loss.backward()
    optimizer.step()

# Evaluate model on test data
with torch.no_grad():
    output = model(test_data_tensor)
    predictions = torch.sigmoid(output)
    correct = ((predictions > 0.5).int() == test_labels_tensor.view(-1, 1).int()).sum().item()
    accuracy = correct / test_labels.shape[0]
    print(f'Test accuracy: {accuracy}')


Test accuracy: 0.44485294117647056
